/**
 * Detox E2E configuration.
 *
 * This project is Expo-managed.
 * Detox requires native projects generated via `expo prebuild`.
 */

module.exports = {
  testRunner: {
    args: {
      $0: 'jest',
      config: 'e2e/jest.config.js',
    },
    jest: {
      setupTimeout: 120000,
    },
  },
  apps: {
    'ios.sim.debug': {
      type: 'ios.app',
      // Produced by xcodebuild when using derivedDataPath=ios/build
      binaryPath:
        'ios/build/Build/Products/Release-iphonesimulator/DatabaseLaboratory.app',
      // Requires ios/ to exist (generated by `expo prebuild -p ios`)
      build:
        'xcodebuild -workspace ios/DatabaseLaboratory.xcworkspace -scheme DatabaseLaboratory -configuration Release -sdk iphonesimulator -derivedDataPath ios/build',
    },

    'android.emu.debug': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      testBinaryPath:
        'android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk',
      build:
        'cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug',
    },

    'android.emu.release': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/release/app-release.apk',
      testBinaryPath:
        'android/app/build/outputs/apk/androidTest/release/app-release-androidTest.apk',
      build:
        'cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release',
    },
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: {
        type: 'iPhone 15',
      },
    },

    emulator: {
      type: 'android.emulator',
      device: {
        avdName: 'Pixel_6',
      },
    },
  },
  configurations: {
    'ios.sim.debug': {
      device: 'simulator',
      app: 'ios.sim.debug',
    },

    'android.emu.debug': {
      device: 'emulator',
      app: 'android.emu.debug',
    },

    'android.emu.release': {
      device: 'emulator',
      app: 'android.emu.release',
    },
  },
};
